# general parameters
data_path: data
save_path: runs/1
device: 'gpu'

# dataset
dataset: 'new'
action_repetitions: 1
split_ratio: 4

# training parameters
total_epochs: 10000
batch_size: 32

# adam optimizer parameters
initial_learning_rate: 0.0001
beta_1: 0.9
beta_2: 0.999

# model architecture parameters 
# (set style=0 for classic VAE)
content_dim: 10
style_dim: 10
keep_style: True
update_prior: False

in_channels: 195
hidden_dims: [32, 32, 32, 32]
kernels: [6, 6, 5, 4]
strides: [4, 4, 2, 2]
paddings: [1, 1, 1, 0]

# loss parameters
content_coef: 1.0
style_coef: 1.0
beta_VAE: 0.1
reduction: 'mean'
beta_NLL: 1.0
weight_style:
